PSST-7209: Bump bindgen to version 0.69.0
With the update to fedora 40 we move to clang 18.x which caused issues
compiling the bindings in this crate such as:

       Compiling regex v1.10.4
       Compiling grpcio-sys v0.12.0+1.46.5-patched-starry.1 (/home/jenkins/grpc-rs/grpc-sys)
    error[E0412]: cannot find type `gpr_timespec` in this scope
     --> grpc-sys/src/grpc_wrap.rs:7:6
      |
    7 | impl gpr_timespec {
      |      ^^^^^^^^^^^^ not found in this scope

For some reason, that `gpr_timespec` does not make it into the
grpc-sys/bindings/bindings.rs generated file when using bindgen 0.62.0 -
but upgrading to 0.69.0 fixes this and compilation succeeds.